apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ga-offline-package-s3
spec:
  secretStoreRef:
    name: ee-gcp-sm
    kind: ClusterSecretStore
  target:
    name: ga-offline-package-s3
  dataFrom:
    - extract:
        # inner keys:
        # - bucket_name
        # - config
        # - credentials
        key: ga_offline_pkg_s3_json
