apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: image-delivery-ops-config-tidbx
spec:
  secretStoreRef:
    name: ee-gcp-sm
    kind: ClusterSecretStore
  target:
    name: image-delivery-ops-config-tidbx
  data:
    - secretKey: debug
      remoteRef:
        key: tidbx-ops-config-debug
    - secretKey: dev
      remoteRef:
        key: tidbx-ops-config-dev
    - secretKey: prod
      remoteRef:
        key: tidbx-ops-config-prod
