apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.yaml
  - image-delivery-notify-config-tidbx.yaml
  - image-delivery-ops-config-tidbx.yaml
  - mac-ssh-credentials.yaml
