---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: el-public
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: "${domain}"
      http:
        paths:
          - pathType: Prefix
            path: "${path_for_hook}(/|$)(.*)"
            backend:
              service:
                name: el-public
                port:
                  name: http-listener
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: el-internal
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: "${domain_internal}"
      http:
        paths:
          - pathType: Prefix
            path: "${path_for_hook}(/|$)(.*)"
            backend:
              service:
                name: el-internal
                port:
                  name: http-listener
