---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: el-public
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: "${domain}"
      http:
        paths:
          - pathType: Prefix
            path: "${path_for_el_public}(/|$)(.*)"
            backend:
              service:
                name: el-github
                port:
                  name: http-listener
