apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../_base
  - cluster-policies
  - brc
  - tekton
  - publisher
  - zot # experiment
  - buildbarn # experiment
  - jenkins/beta # experiment
