apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tekton-config-trigger-triggers
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: ci
    namespace: flux-system
  path: ./tekton/v1/triggers/triggers/env-gcp
  prune: true
