apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../_base
  - namespace.yaml
  - jenkins
  - jenkins-pingkai.yaml
  - greenhouse
  - ats
  - goproxy
  - prow-worker
  - kafka
  - cloudevents-server
  - boskos
  - dl
  - harbor
  - redis
  - chatops-lark
