apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: publisher
resources:
  - namespace.yaml
  - redis
  - kafka
  - publisher-packages-config.yaml
  - external-secrets
  - releases.yaml
