---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: publisher-packages-config
spec:
  targetNamespace: publisher
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: artifacts
    namespace: flux-system
  path: ./packages
  prune: true
