apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - publisher-config-prod.yaml
  - publisher-config-staging.yaml
  - tiup-credentials-prod.yaml
  - tiup-credentials-staging.yaml
