apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: publisher-config-staging
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: ee-gcp-sm
  target:
    name: publisher-config-staging
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        service.yaml: |
          event_source: "http://publisher-staging.apps.svc"
          kafka:
            brokers:
              - cluster-cd-kafka-bootstrap.kafka.svc:9092
            topic: cd-publishing-requests-staging
            client_id: publisher-staging
          redis:
            addr: "redis-master.redis:6379"
            db: 0
            password: {{ .data.redis_password }}
        worker.yaml: |
          tiup:
            kafka:
              brokers:
                - cluster-cd-kafka-bootstrap.kafka.svc:9092
              topic: cd-publishing-requests-staging
              consumer_group: publisher-staging-tiup

            options:
              mirror_url: {{ .data.tiup_mirror_url}}
              lark_webhook_url: {{ .data.lark_webhook_url }}
              nightly_interval: 12h
            redis:
              addr: "redis-master.redis:6379"
              db: 0
              password: {{ .data.redis_password }}

          file_server:
            kafka:
              brokers:
                - cluster-cd-kafka-bootstrap.kafka.svc:9092
              topic: cd-publishing-requests-staging
              consumer_group: publisher-staging-fs

            redis:
              addr: "redis-master.redis:6379"
              db: 0
              password: {{ .data.redis_password }}

            options:
              lark_webhook_url: {{ .data.lark_webhook_url }}
              s3.endpoint: {{ .data.S3_REGION_ENDPOINT }}
              s3.region: {{ .data.S3_REGION }}
              s3.bucket_name: {{ .data.S3_BUCKET }}
              s3.access_key: {{ .data.S3_ACCESS_KEY }}
              s3.secret_key: {{ .data.S3_SECRET_KEY }}

  data:
    - secretKey: redis_password
      remoteRef:
        key: prod2_publisher_redis_password
    - secretKey: tiup-prod-mirror-url
      remoteRef:
        key: prod2_publisher_redis_password
    - secretKey: lark_webhook_url
      remoteRef:
        key: prod2_publisher_failure_lark_webhook_url
  dataFrom:
    - extract:
        # json object contains keys: S3_*
        key: prod2_publisher_fileserver_s3_json
