apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tekton-config-pipelines
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: ci
    namespace: flux-system
  path: ./tekton/v1/pipelines
  prune: true
  force: true
  dependsOn:
    - name: tekton-config-tasks
