---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: publisher-packages-config
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: artifacts
    namespace: flux-system
  path: ./packages
  prune: true
  healthChecks:
    - name: packages-config
      kind: ConfigMap
