apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: publisher
resources:
  # Please do not change the order of these resources.
  - redis
  - kafka
  - config.yaml
  - external-secrets
