apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - publisher.yaml
  - ext-ingress.yaml
  - worker-tiup-fileserver.yaml
  - worker-tiup-prod.yaml
  - worker-tiup-staging.yaml
