---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fwd-prod2-publisher
  namespace: tekton-pipelines
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "${path_for_publisher}/$2"

    # Tell ingress-nginx to talk to the service's DNS name (works with ExternalName)
    nginx.ingress.kubernetes.io/service-upstream: "true"

    # Ensure the upstream sees the correct Host header
    nginx.ingress.kubernetes.io/upstream-vhost: "${domain_internal2}"

    # Upstream is HTTP
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

spec:
  ingressClassName: nginx
  rules:
    - host: "${domain}"
      http:
        paths:
          - pathType: ImplementationSpecific
            path: "${path_for_publisher}(/|$)(.*)"
            backend:
              service:
                name: fwd-prod2
                port:
                  name: http
