apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress-dashboard.yaml
  - ingress-event-listener.yaml
  - ingress-forward-prod2.yaml
  - ingress-forward-prod2-publisher.yaml
