apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../_base
  - cluster-policies
  # applications
  - cla-assistant
  - prow
  - tekton
  - kafka
  - cloudevents-server
  # workloads
  - acr-runners
  - jenkins-agents
