---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gateway-config
  namespace: infra
spec:
  targetNamespace: infra
  dependsOn:
    - name: envoy-gateway-release
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./infrastructure/prod2/gateways/config
  prune: true
