# apiVersion: networking.gke.io/v1
# kind: HealthCheckPolicy
# metadata:
#   name: controller-backend
# spec:
#   default:
#     config:
#       type: HTTP
#       httpHealthCheck:
#         port: 8080
#         requestPath: "${INGRESS_PATH}/login"
#         response: "200"
#   targetRef:
#     group: ""
#     kind: Service
#     name: jenkins
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: controller
  namespace: jenkins
spec:
  parentRefs:
    - kind: Gateway
      name: external-https
      namespace: infra
  hostnames:
    - "${INGRESS_HOST}"
  rules:
    - backendRefs:
        - name: jenkins
          port: 8080
      matches:
        - path:
            type: PathPrefix
            value: "${INGRESS_PATH}"
