apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret-jenkins-cache.yaml
  - secret-github.yaml
  - secret-codecov.yaml
  - secret-harbor.yaml
  - secret-docs-cn.yaml
  - secret-ks3util.yaml
