apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tekton-config-trigger-templates
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: ci
    namespace: flux-system
  path: ./tekton/v1/triggers/templates
  prune: true
  postBuild:
    substitute:
      STORAGE_CLASSNAME_RWO: openebs-single-replica
      STORAGE_CLASSNAME_RWO_AMD64: openebs-single-replica
      STORAGE_CLASSNAME_RWO_ARM64: openebs-hostpath
      # STORAGE_CLASSNAME_RWM: not-used-yet
