apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-ssh-secret
spec:
  secretStoreRef:
    name: ee-gcp-sm
    kind: ClusterSecretStore
  target:
    name: github-ssh-secret
    template:
      type: kubernetes.io/ssh-auth
      metadata:
        annotations:
          tekton.dev/git-0: github.com
  dataFrom:
    - extract:
        # json object contains keys: `ssh-privatekey`, `ssh-publickey`.
        key: github-bot-ssh-rsa-json
