apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-pat-secret
spec:
  secretStoreRef:
    name: ee-gcp-sm
    kind: ClusterSecretStore
  target:
    name: github-pat-secret
    template:
      type: kubernetes.io/basic-auth
      metadata:
        annotations:
          tekton.dev/git-0: https://github.com
  data:
    - secretKey: username
      remoteRef:
        key: github-bot-username
    - secretKey: password
      remoteRef:
        key: github-bot-token
