apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: image-release-cred
spec:
  secretStoreRef:
    name: ee-gcp-sm
    kind: ClusterSecretStore
  target:
    name: image-release-cred
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: gsa.json
      remoteRef:
        key: gcp_sa_json_ee-releaser
    - secretKey: .dockerconfigjson
      remoteRef:
        key: prod2_ee-releasor_dockerconfig_json
  refreshInterval: 1h
