apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ks3utilconfig
spec:
  secretStoreRef:
    name: ee-gcp-sm
    kind: ClusterSecretStore
  target:
    name: ks3utilconfig
  data:
    - secretKey: .ks3utilconfig
      remoteRef:
        key: prod2_ks3utilconfig-ee
  refreshInterval: 1h
