apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.yaml
  - github-pat-secret.yaml
  - github-ssh-secret.yaml
  - image-release-cred.yaml
  - mac-ssh-credentials.yaml
  - ks3utilconfig.yaml
  - ga-offline-package-s3.yaml
