apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-agent.yaml
  - release.yaml
secretGenerator:
  - name: jenkins-release-values
    files:
      - values1.yaml=values-controller.yaml
      - values2.yaml=values-controller-plugins.yaml
      - values3.yaml=values-JCasC.yaml
      - values4.yaml=values-rbac.yaml
configurations:
  - kustomize-config.yaml
