apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: v1-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: ee-gcp-sm
  target:
    name: v1-config
    creationPolicy: Owner
  data:
    - secretKey: config.yaml
      remoteRef:
        key: prod2_tibuild_v1_config_yaml
