apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../_base
  - namespace.yaml
  - openebs
  - nfs-pvc-provisioner
  - nginx
  - secret-generator
  - external-secrets
  - kyverno
  - operators
