apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  # renovate: datasource=github-releases depName=tektoncd/operator versioning=semver
  - https://storage.googleapis.com/tekton-releases/operator/previous/v0.77.0/release.yaml
  - operator-config.yaml
  - operator-manual-approval-gate.yaml
  # renovate: datasource=github-releases depName=tektoncd/operator versioning=semver
  - https://github.com/tektoncd/pipeline/raw/refs/tags/v1.3.1/optional_config/enable-log-access-to-controller/clusterrole.yaml
  - https://github.com/tektoncd/pipeline/raw/refs/tags/v1.3.1/optional_config/enable-log-access-to-controller/clusterrolebinding.yaml
  # - https://storage.googleapis.com/tekton-releases-nightly/pipelines-in-pipelines/latest/release.yaml
