apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - publisher-server-config.yaml
  - publisher-worker-config-fileserver.yaml
  - publisher-worker-config-tiup-prod.yaml
  - publisher-worker-config-tiup-staging.yaml
  - tiup-credentials-prod.yaml
  - tiup-credentials-staging.yaml
