apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: v2-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: ee-gcp-sm
  target:
    name: v2-config
    creationPolicy: Owner
  data:
    - secretKey: config.yaml
      remoteRef:
        key: prod2_tibuild_v2_config_yaml
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ingress-auth-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ee-gcp-sm
    kind: ClusterSecretStore
  target:
    name: ingress-auth-secret
    creationPolicy: Owner
  data:
    - secretKey: auth
      remoteRef:
        key: tidbx-ops-client-tibuild-v2-basic-auth
