apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /api/v2/$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: ingress-auth-secret
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
  name: v2-tibuild-v2-auth
  namespace: tibuild
spec:
  ingressClassName: nginx
  rules:
    - host: do2.pingcap.net
      http:
        paths:
          - backend:
              service:
                name: v2-tibuild-v2
                port:
                  number: 80
            path: /tibuild/api/v2(/|$)(.*)
            pathType: Prefix
