---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tekton-configs
spec:
  interval: 1m0s
  targetNamespace: ee-cd
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./apps/prod2/tekton/configs
  dependsOn:
    - name: tekton-setup
  prune: true
  patches:
    - target:
        kind: Kustomization
        group: kustomize.toolkit.fluxcd.io
        name: tekton-config-.+
      patch: |-
        - op: add
          path: /spec/targetNamespace
          value: ee-cd
  postBuild:
    substitute:
      domain: do.pingcap.net # not available yet.
      domain_internal: internal2-do.pingcap.net
      path_for_hook: /tekton
