apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tidbx-docker-config
spec:
  secretStoreRef:
    name: ee-gcp-sm
    kind: ClusterSecretStore
  target:
    name: tidbx-docker-config
    template:
      engineVersion: v2
      type: Opaque
      metadata:
        annotations:
          jenkins.io/credentials-description: docker auth credintial for TiDB-X OCI artifacts
        labels:
          jenkins.io/credentials-type: secretFile
      data:
        filename: docker.config
        data: "{{ .data }}"
  data:
    - secretKey: data
      remoteRef:
        key: gcp_tidbx_dockerconfig_json
  refreshInterval: 1h
